trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2 
  inputs:
    command: 'build'
    projects: 'SauceOpsDesktop.sln'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  env:
    OPSENG_SAUCE_API_KEY: $(OPSENG_SAUCE_API_KEY)
    OPSENG_SAUCE_USER_NAME: $(OPSENG_SAUCE_USER_NAME)
  inputs:
    command: 'test'
    projects: 'UnitTests/UnitTests.csproj'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  env:
    OPSENG_SAUCE_API_KEY: $(OPSENG_SAUCE_API_KEY)
    OPSENG_SAUCE_USER_NAME: $(OPSENG_SAUCE_USER_NAME)
  inputs:
    command: 'test'
    projects: 'SauceOps/SauceOps.csproj'
    arguments: '-c Release'